# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Default box IP address
  # This is the IP address that your host will communicate to the guest
  # through. Change if you're already on the `192.168.33.x` subnet.
  # private_ip = "192.168.33.15"

  # Enable agent forwarding on vagrant ssh commands. This allows you to use
  # identities established on the host machine inside the guest. See the manual
  # for `ssh-add`
  # config.ssh.forward_agent = true
  # config.ssh.forward_x11   = true

  # Default Ubuntu Server 12.04 box -- once downloaded, Vagrant will use the cached version
  config.vm.box     = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # config.vm.hostname = "tessera-hadoop-mr2"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network(:private_network, :ip => private_ip)
  
  config.vm.network :forwarded_port, guest: 50070, host: 60070  
  config.vm.network :forwarded_port, guest: 50075, host: 60075  
  config.vm.network :forwarded_port, guest: 50030, host: 60030
  config.vm.network :forwarded_port, guest: 50060, host: 60060
  # config.vm.network :forwarded_port, guest: 8787, host: 9787
  config.vm.network :forwarded_port, guest: 3838, host: 4838
  config.vm.network :forwarded_port, guest: 8088, host: 9088
  config.vm.network :forwarded_port, guest: 80, host: 9787

  config.vm.provider :virtualbox do |vb|
    # vb.customize(["modifyvm", :id, "--natdnshostresolver1", "off"  ])
    # vb.customize(["modifyvm", :id, "--natdnsproxy1",        "off"  ])
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.synced_folder(".", "/vagrant",
    :owner => "vagrant",
    :group => "vagrant",
    :mount_options => ['dmode=777','fmode=777']
  )

  current_dir = File.dirname(__FILE__)

  config.vm.provision(
    :shell,
    :inline => "chmod +x /vagrant/install.sh"
  )
  config.vm.provision(
    :shell,
    :inline => "/vagrant/install.sh"
  )

  config.vm.provision(
    :shell,
    :inline => "chmod +x /vagrant/tessera.sh"
  )
  config.vm.provision(
    :shell,
    :inline => "/vagrant/tessera.sh"
  )

  config.vm.post_up_message="Tessera virtual machine has been provisioned...
To work from command line: SSH into the machine with 'vagrant ssh'
To work from RStudio IDE: navigate to 'localhost:8000' in your web browser with credentials vagrant:vagrant"

end
