# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_plugin 'vagrant-aws'
Vagrant.require_plugin 'vagrant-omnibus'
Vagrant.configure("2") do |config|
#config.omnibus.chef_version = :latest
config.vm.synced_folder '.', '/vagrant', :disabled => true
config.vm.box = "dummy"
config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
# Provider
config.vm.provider :aws do |aws, override|
aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']    
aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY'] 
aws.keypair_name = "KeyName"
aws.ami = "ami-cc5be9a4" #Ubuntu 12.04 LTS
aws.region = "us-east-1"
#aws.instance_type = "t1.micro"
aws.security_groups = ["default"]
override.ssh.username = "ubuntu"
#override.ssh.username = "vagrant"
override.ssh.private_key_path = "path-to-pem"
end
config.vm.provision(
:shell,
:inline => "cd /tmp/;mkdir vagrant-script;cd vagrant-script; wget https://raw.githubusercontent.com/ashrith/install-vagrant/master/aws.cdh5mr2-rhipe0.75/install.sh -O install.sh;wget https://raw.githubusercontent.com/ashrith/install-vagrant/master/aws.cdh5mr2-rhipe0.75/tessera.sh -O tessera.sh; chmod +x install.sh;chmod +x tessera.sh;./install.sh;./tessera.sh;"
)
end
